--CARGA ENTRE AMAZON S3 E REDSHIFT

jdbc:redshift://redshift-cluster-1..us-east-2.redshift.amazonaws.com:5439/dev

copy MICRODADOS_ENEM_2017 from 's3://enem2017diogo/rawdata/MICRODADOS_ENEM_2017.csv' access_key_id '' secret_access_key '' DELIMITER ';' IGNOREHEADER 1 ACCEPTINVCHARS;

copy POP_IDH from 's3://enem2017diogo/rawdata/POP_IDH.csv' access_key_id '' secret_access_key '' DELIMITER ';' IGNOREHEADER 1 ACCEPTINVCHARS;


--DDL
--STAGE

CREATE TABLE MICRODADOS_ENEM_2017(

NU_INSCRICAO	bigint,
NU_ANO	real,
CO_MUNICIPIO_RESIDENCIA	real,
NO_MUNICIPIO_RESIDENCIA	varchar(200),
CO_UF_RESIDENCIA	real,
SG_UF_RESIDENCIA	varchar(200),
NU_IDADE	real,
TP_SEXO	varchar(200),
TP_ESTADO_CIVIL	real,
TP_COR_RACA	real,
TP_NACIONALIDADE	real,
CO_MUNICIPIO_NASCIMENTO	real,
NO_MUNICIPIO_NASCIMENTO	varchar(200),
CO_UF_NASCIMENTO	real,
SG_UF_NASCIMENTO	varchar(200),
TP_ST_CONCLUSAO	real,
TP_ANO_CONCLUIU	real,
TP_ESCOLA	real,
TP_ENSINO	real,	
IN_TREINEIRO	real,
CO_ESCOLA	real,
CO_MUNICIPIO_ESC	real,
NO_MUNICIPIO_ESC	varchar(200),
CO_UF_ESC	real,
SG_UF_ESC	varchar(200),
TP_DEPENDENCIA_ADM_ESC	real,
TP_LOCALIZACAO_ESC	real,
TP_SIT_FUNC_ESC	real,
IN_BAIXA_VISAO	real,
IN_CEGUEIRA	real,
IN_SURDEZ	real,
IN_DEFICIENCIA_AUDITIVA	real,
IN_SURDO_CEGUEIRA	real,
IN_DEFICIENCIA_FISICA	real,
IN_DEFICIENCIA_MENTAL	real,
IN_DEFICIT_ATENCAO	real,
IN_DISLEXIA	real,
IN_DISCALCULIA	real,
IN_AUTISMO	real,
IN_VISAO_MONOCULAR	real,
IN_OUTRA_DEF	real,
IN_GESTANTE	real,
IN_LACTANTE	real,
IN_IDOSO	real,
IN_ESTUDA_CLASSE_HOSPITALAR	real,
IN_SEM_RECURSO	real,
IN_BRAILLE	real,
IN_AMPLIADA_24	real,
IN_AMPLIADA_18	real,
IN_LEDOR	real,
IN_ACESSO	real,
IN_TRANSCRICAO	real,
IN_LIBRAS	real,
IN_LEITURA_LABIAL	real,
IN_MESA_CADEIRA_RODAS	real,
IN_MESA_CADEIRA_SEPARADA	real,
IN_APOIO_PERNA	real,
IN_GUIA_INTERPRETE	real,
IN_COMPUTADOR	real,
IN_CADEIRA_ESPECIAL	real,
IN_CADEIRA_CANHOTO	real,
IN_CADEIRA_ACOLCHOADA	real,
IN_PROVA_DEITADO	real,
IN_MOBILIARIO_OBESO	real,
IN_LAMINA_OVERLAY	real,
IN_PROTETOR_AURICULAR	real,
IN_MEDIDOR_GLICOSE	real,
IN_MAQUINA_BRAILE	real,
IN_SOROBAN	real,
IN_MARCA_PASSO	real,
IN_SONDA	real,
IN_MEDICAMENTOS	real,
IN_SALA_INDIVIDUAL	real,
IN_SALA_ESPECIAL	real,
IN_SALA_ACOMPANHANTE	real,
IN_MOBILIARIO_ESPECIFICO	real,
IN_MATERIAL_ESPECIFICO	real,
IN_NOME_SOCIAL	real,
CO_MUNICIPIO_PROVA	real,
NO_MUNICIPIO_PROVA	varchar(200),
CO_UF_PROVA	varchar(200),
SG_UF_PROVA	varchar(200),
TP_PRESENCA_CN	real,
TP_PRESENCA_CH	real,
TP_PRESENCA_LC	real,
TP_PRESENCA_MT	real,
CO_PROVA_CN	real,
CO_PROVA_CH	real,
CO_PROVA_LC	real,
CO_PROVA_MT	real,
NU_NOTA_CN	real,
NU_NOTA_CH	real,
NU_NOTA_LC	real,
NU_NOTA_MT	real,
TX_RESPOSTAS_CN	varchar(200),
TX_RESPOSTAS_CH	varchar(200),
TX_RESPOSTAS_LC	varchar(200),
TX_RESPOSTAS_MT	varchar(200),
TP_LINGUA	real,
TX_GABARITO_CN	varchar(200),
TX_GABARITO_CH	varchar(200),
TX_GABARITO_LC	varchar(200),
TX_GABARITO_MT	varchar(200),
TP_STATUS_REDACAO	real,
NU_NOTA_COMP1	real,
NU_NOTA_COMP2	real,
NU_NOTA_COMP3	real,
NU_NOTA_COMP4	real,
NU_NOTA_COMP5	real,
NU_NOTA_REDACAO	real,
Q001	varchar(200),
Q002	varchar(200),
Q003	varchar(200),
Q004	varchar(200),
Q005	real,
Q006	varchar(200),
Q007	varchar(200),
Q008	varchar(200),
Q009	varchar(200),
Q010	varchar(200),
Q011	varchar(200),
Q012	varchar(200),
Q013	varchar(200),
Q014	varchar(200),
Q015	varchar(200),
Q016	varchar(200),
Q017	varchar(200),
Q018	varchar(200),
Q019	varchar(200),
Q020	varchar(200),
Q021	varchar(200),
Q022	varchar(200),
Q023	varchar(200),
Q024	varchar(200),
Q025	varchar(200),
Q026	varchar(200),
Q027	varchar(200));

--TABELAS AUXILIARES OUTRAS FONTES

CREATE TABLE POP_IDH(
CO_MUNICIPIO_PROVA real,
NO_MUNICIPIO_PROVA varchar(200),
POP real,
IDH real
);

DROP TABLE POP_IDH_SCORE;

CREATE TABLE POP_IDH_SCORE(
SG_UF_PROVA	varchar(200),
CO_MUNICIPIO_PROVA real,
NO_MUNICIPIO_PROVA varchar(200),
POP real,
IDH real,
NOTA_MEDIA real
);

INSERT INTO POP_IDH_SCORE(CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, POP, IDH)
(SELECT CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, POP, IDH FROM POP_IDH);

DROP TABLE MUNICIPIO_NOTA_MEDIA;

CREATE TABLE MUNICIPIO_NOTA_MEDIA(
CO_MUNICIPIO_PROVA real,
NOTA_MEDIA real
);

TRUNCATE TABLE MUNICIPIO_NOTA_MEDIA;

INSERT INTO MUNICIPIO_NOTA_MEDIA
(SELECT DISTINCT CO_MUNICIPIO_PROVA, 
((SUM(NU_NOTA_REDACAO)/COUNT(NU_INSCRICAO))+(SUM(NU_NOTA_CN)/COUNT(NU_INSCRICAO))+(SUM(NU_NOTA_CH)/COUNT(NU_INSCRICAO))+(SUM(NU_NOTA_LC)/COUNT(NU_INSCRICAO))++(SUM(NU_NOTA_MT)/COUNT(NU_INSCRICAO)))/5  NOTA_MEDIA 
FROM MICRODADOS_ENEM_2017 
where TP_PRESENCA_CN = 1 and
TP_PRESENCA_CH  = 1 and 
TP_PRESENCA_LC = 1 and 
TP_PRESENCA_MT = 1 and 
TP_STATUS_REDACAO = 1 
GROUP BY CO_MUNICIPIO_PROVA);

UPDATE POP_IDH_SCORE SET NOTA_MEDIA = (SELECT NOTA_MEDIA FROM MUNICIPIO_NOTA_MEDIA WHERE MUNICIPIO_NOTA_MEDIA.CO_MUNICIPIO_PROVA = POP_IDH_SCORE.CO_MUNICIPIO_PROVA);

DELETE FROM POP_IDH_SCORE WHERE NOTA_MEDIA IS NULL;

UPDATE POP_IDH_SCORE SET SG_UF_PROVA = (SELECT SG_UF_PROVA FROM DIM_LOCAL WHERE DIM_LOCAL.CO_MUNICIPIO_PROVA =  POP_IDH_SCORE.CO_MUNICIPIO_PROVA);

--DIMENSÕES
DROP TABLE DIM_LOCAL;

CREATE TABLE DIM_LOCAL(
CO_MUNICIPIO_PROVA	real,
NO_MUNICIPIO_PROVA	varchar(200),
SG_UF_PROVA	varchar(200),
TP_POP	varchar(200),
TP_IDH varchar(200),
primary key(CO_MUNICIPIO_PROVA)
);


CREATE TABLE DIM_CANDIDATO(
NU_INSCRICAO	bigint,
TP_SEXO varchar(200),
TP_ESTADO_CIVIL varchar(200),
TP_COR_RACA varchar(200),
TP_ESCOLA varchar(200),
TP_ANO_CONCLUIU varchar(200),
primary key(NU_INSCRICAO)
);


CREATE TABLE DIM_RENDA(
CO_RENDA varchar(200),
NO_RENDA varchar(200),
primary key(CO_RENDA)
);

--FATO

DROP TABLE FATOENEM;

CREATE TABLE FATOENEM(
NU_INSCRICAO	bigint,
CO_MUNICIPIO_PROVA	real,
CO_RENDA varchar(200),
NU_NOTA_CN	real,
NU_NOTA_CH	real,
NU_NOTA_LC	real,
NU_NOTA_MT	real,
NU_NOTA_REDACAO	real,
primary key(NU_INSCRICAO, CO_MUNICIPIO_PROVA, CO_RENDA),
foreign key(NU_INSCRICAO) references DIM_CANDIDATO(NU_INSCRICAO),
foreign key(CO_RENDA) references DIM_RENDA(CO_RENDA)
);

--DML DIMENSIONAL
--CARGA DIMENSÕES

--DIMENSÃO LOCAL
TRUNCATE TABLE DIM_LOCAL;

INSERT INTO DIM_LOCAL (CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, SG_UF_PROVA)
(SELECT DISTINCT CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, SG_UF_PROVA FROM microdados_enem_2017);

UPDATE DIM_LOCAL SET NO_MUNICIPIO_PROVA = (SELECT DISTINCT NO_MUNICIPIO_PROVA FROM POP_IDH WHERE DIM_LOCAL.CO_MUNICIPIO_PROVA = POP_IDH.CO_MUNICIPIO_PROVA);

UPDATE DIM_LOCAL SET TP_POP = 'Menor que 5.000 habitantes' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE POP <= 5000);
UPDATE DIM_LOCAL SET TP_POP = 'Entre 5.001 e 20.000 habitantes' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE POP > 5000 AND POP <= 20000);
UPDATE DIM_LOCAL SET TP_POP = 'Entre 20.001 e 50.000 habitantes' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE POP > 20000 AND POP <= 50000);
UPDATE DIM_LOCAL SET TP_POP = 'Entre 50.001 e 100.000 habitantes' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE POP > 50000 AND POP <= 100000);
UPDATE DIM_LOCAL SET TP_POP = 'Maior que 100.000 habitantes' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE POP > 100000);


UPDATE DIM_LOCAL SET TP_IDH = 'Menor que 0,5' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE IDH <= 0.5);
UPDATE DIM_LOCAL SET TP_IDH = 'Entre 0,5 e 0,6' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE IDH > 0.5 AND IDH <= 0.6);
UPDATE DIM_LOCAL SET TP_IDH = 'Entre 0,6 e 0,7' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE IDH > 0.6 AND IDH <= 0.7);
UPDATE DIM_LOCAL SET TP_IDH = 'Entre 0,7 E 0,8' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE IDH > 0.7 AND IDH <= 0.8);
UPDATE DIM_LOCAL SET TP_IDH = 'Maior que 0,8' WHERE CO_MUNICIPIO_PROVA IN (SELECT CO_MUNICIPIO_PROVA FROM POP_IDH WHERE IDH > 0.8);

--DIMENSÃO CANDIDATO

INSERT INTO DIM_CANDIDATO
(SELECT DISTINCT NU_INSCRICAO, TP_SEXO, TP_ESTADO_CIVIL, TP_COR_RACA, TP_ESCOLA, TP_ANO_CONCLUIU FROM microdados_enem_2017);


UPDATE DIM_CANDIDATO SET TP_ESTADO_CIVIL = 'Solteiro(a)' WHERE TP_ESTADO_CIVIL = 0;
UPDATE DIM_CANDIDATO SET TP_ESTADO_CIVIL = 'Casado(a)/Mora com companheiro(a)' WHERE TP_ESTADO_CIVIL = 1;
UPDATE DIM_CANDIDATO SET TP_ESTADO_CIVIL = 'Divorciado(a)/Desquitado(a)/Separado(a)' WHERE TP_ESTADO_CIVIL = 2;
UPDATE DIM_CANDIDATO SET TP_ESTADO_CIVIL = 'Viúvo(a)' WHERE TP_ESTADO_CIVIL = 3;

UPDATE DIM_CANDIDATO SET TP_COR_RACA = 'Não declarado' WHERE TP_COR_RACA = 0;
UPDATE DIM_CANDIDATO SET TP_COR_RACA = 'Branca' WHERE TP_COR_RACA = 1;
UPDATE DIM_CANDIDATO SET TP_COR_RACA = 'Preta' WHERE TP_COR_RACA = 2;
UPDATE DIM_CANDIDATO SET TP_COR_RACA = 'Parda' WHERE TP_COR_RACA = 3;
UPDATE DIM_CANDIDATO SET TP_COR_RACA = 'Amarela' WHERE TP_COR_RACA = 4;

UPDATE DIM_CANDIDATO SET TP_ESCOLA = 'Não Respondeu' WHERE TP_ESCOLA = 1;
UPDATE DIM_CANDIDATO SET TP_ESCOLA = 'Pública' WHERE TP_ESCOLA = 2;
UPDATE DIM_CANDIDATO SET TP_ESCOLA = 'Privada' WHERE TP_ESCOLA = 3;
UPDATE DIM_CANDIDATO SET TP_ESCOLA = 'Exterior' WHERE TP_ESCOLA = 4;

UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = 'Não informado' WHERE TP_ANO_CONCLUIU = 0;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2016' WHERE TP_ANO_CONCLUIU = 1;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2015' WHERE TP_ANO_CONCLUIU = 2;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2014' WHERE TP_ANO_CONCLUIU = 3;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2013' WHERE TP_ANO_CONCLUIU = 4;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2012' WHERE TP_ANO_CONCLUIU = 5;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2011' WHERE TP_ANO_CONCLUIU = 6;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2010' WHERE TP_ANO_CONCLUIU = 7;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2009' WHERE TP_ANO_CONCLUIU = 8;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2008' WHERE TP_ANO_CONCLUIU = 9;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = '2007' WHERE TP_ANO_CONCLUIU = 10;
UPDATE DIM_CANDIDATO SET TP_ANO_CONCLUIU = 'Antes de 2007' WHERE TP_ANO_CONCLUIU = 11;
--DIMENSÃO ÁREA

INSERT INTO DIM_AREA (SG_AREA, NO_AREA) VALUES ('CH','Ciências Humanas');
INSERT INTO DIM_AREA (SG_AREA, NO_AREA) VALUES ('CN','Ciências da Natureza');
INSERT INTO DIM_AREA (SG_AREA, NO_AREA) VALUES ('LC','Linguagens e Códigos');
INSERT INTO DIM_AREA (SG_AREA, NO_AREA) VALUES ('MT','Matemática');
INSERT INTO DIM_AREA (SG_AREA, NO_AREA) VALUES ('RD','Redação');

--DIMENSÃO RENDA
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('A',	'Nenhuma renda');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('B', 'Até R$ 937,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('C', 'De R$ 937,01 até R$ 1.405,50');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('D', 'De R$ 1.405,51 até R$ 1.874,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('E', 'De R$ 1.874,01 até R$ 2.342,50');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('F', 'De R$ 2.342,51 até R$ 2.811,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('G', 'De R$ 2.811,01 até R$ 3.748,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('H', 'De R$ 3.748,01 até R$ 4.685,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('I', 'De R$ 4.685,01 até R$ 5.622,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('J', 'De R$ 5.622,01 até R$ 6.559,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('K', 'De R$ 6.559,01 até R$ 7.496,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('L', 'De R$ 7.496,01 até R$ 8.433,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('M', 'De R$ 8.433,01 até R$ 9.370,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('N', 'De R$ 9.370,01 até R$ 11.244,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('O', 'De R$ 11.244,01 até R$ 14.055,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('P', 'De R$ 14.055,01 até R$ 18.740,00');
INSERT INTO DIM_RENDA (CO_RENDA, NO_RENDA) VALUES ('Q', 'Mais de R$ 18.740,00');


--FATO 
TRUNCATE TABLE FATOENEM;

INSERT INTO FATOENEM(NU_INSCRICAO, CO_MUNICIPIO_PROVA, CO_RENDA, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, NU_NOTA_REDACAO)
(SELECT NU_INSCRICAO, CO_MUNICIPIO_PROVA, Q006, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, NU_NOTA_REDACAO
from microdados_enem_2017
where TP_PRESENCA_CN = 1 and
TP_PRESENCA_CH  = 1 and 
TP_PRESENCA_LC = 1 and 
TP_PRESENCA_MT = 1 and 
TP_STATUS_REDACAO = 1);

--OUTROS

select top 100 * from microdados_enem_2017;

select top 50 * from FATOENEM;

SELECT TOP 50 * FROM DIM_LOCAL;

SELECT TOP 50 * FROM DIM_LOCAL WHERE NO_MUNICIPIO_PROVA LIKE '%CONTAGEM%';

SELECT TOP 50 * FROM POP_IDH;

SELECT TOP 50 * FROM DIM_CANDIDATO;

SELECT TOP 50 * FROM DIM_AREA;

SELECT TOP 50 * FROM FATOENEM;

SELECT TOP 50 * FROM FATOENEM WHERE NU_INSCRICAO = '170001663645';

SELECT * FROM POP_IDH order by no_municipio_prova;

SELECT * FROM POP_IDH_SCORE;

SELECT TOP 1000 * FROM POP_IDH ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE POP > 100000 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE POP > 50000 AND POP <= 100000 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE POP > 20000 AND POP <= 50000 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE POP > 5000 AND POP <= 20000 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE POP <= 5000 ORDER BY POP DESC;


SELECT * FROM POP_IDH WHERE IDH > 0.8 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE IDH > 0.7 AND IDH <= 0.8 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE IDH > 0.6 AND IDH <= 0.7 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE IDH > 0.5 AND IDH <= 0.6 ORDER BY POP DESC;

SELECT * FROM POP_IDH WHERE IDH <= 0.5 ORDER BY POP DESC;

